[config]

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors/matugen.css'
pre_hook = 'killall -9 waybar'
post_hook = 'waybar &'

[templates.zen]
input_path = './templates/zen.css'
output_path = '~/.zen/.shared/matugen.css'

[templates.swaync]
input_path = './templates/colors.css'
output_path = '~/.config/swaync/colors/matugen.css'
pre_hook = 'killall -9 swaync'
post_hook = 'swaync &'

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors/custom/matugen.conf'
post_hook = 'hyprctl reload & hyprshade auto'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/custom/matugen.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
# We would need the following two hooks if we were using polkit-gnome-authentication-agent-1
pre_hook = 'killall -9 /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1'
post_hook = '/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &'
# post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/launchers/shared/matugen.rasi'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/config'
post_hook = "pkill -USR1 cava"

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/styles/matugen.css'

# [templates.qt5ct]
# input_path = '~/.config/matugen/templates/qtct-colors.conf'
# output_path = '~/.config/qt5ct/colors/matugen.conf'
#
# [templates.qt6ct]
# input_path = '~/.config/matugen/templates/qtct-colors.conf'
# output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.discord]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.var/app/dev.vencord.Vesktop/config/vesktop/themes/matugen.css'

[templates.kvlibadwaita]
input_path = '~/.config/matugen/templates/kv-libadwaita-theme.kvconfig'
output_path = '~/.config/Kvantum/KvLibadwaita/KvLibadwaitaDark.kvconfig'

